sudo: required
service: 
  - docker
before_install:
  - docker build -f ./client/Dockerfile.dev -t seyhann/docker-react ./client
script:
  - docker run -e CI=true seyhann/docker-react npm run test

after_success:
  - docker build -t seyhann/multi-client ./client
  - docker build -t seyhann/multi-nginx ./nginx
  - docker build -t seyhann/multi-server ./server
  - docker build -t seyhann/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push seyhann/multi-client
  - docker push seyhann/multi-nginx 
  - docker push seyhann/multi-server
  - docker push seyhann/multi-worker
